### ISSUE TITLE
Problem with display of featured posts

### ISSUE THREAD

**Issue by premiumwp** [premiumwp/manta#18]
Looks like if a post has ever been assigned to a category called “featured” these post show up in the featured posts section

**Comment by ghost** [comment]
There was a bug in the featured post code. This script support featured posts using WordPress sticky posts functionality. It will display up to three sticky posts as featured posts. However, the problem occur when there is no post has been set as sticky. In that case, script displays all posts on that page as featured.
Script will be corrected to address this error.
